### ISSUE TITLE
The read more notation

### ISSUE THREAD

**Issue by jiawei-zhang-a** [ossd-s23/seoeunHong-weekly#1]
Read More Only displayed the date as professor indicated in class

**Comment by jiawei-zhang-a** [comment]
Suggest adding this to correctly control the read-more position

**Comment by seoeunHong** [comment]
What does it mean "correctly control" the read-more position? Could you give me more example how you want me to edit this session?

**Comment by jiawei-zhang-a** [comment]
Sorry for the late reply, I did not know this until browsing my issues and see your post in my repo, You have fixed this issue by adding "
"Congrats!

**Comment by seoeunHong** [comment]
Oh I see yeah I fixed the day after the professor mentioned that, so I did not catch the meaning of your saying. Thanks for opening this issue!
