### ISSUE TITLE
Double Titles

### ISSUE THREAD

**Issue by Charlie-XIAO** [ossd-s23/seoeunHong-weekly#3]
Hi! In your weekly posts, I notice that all of them has two titles. In fact,
```
---
layout: post
title: Week 1
---
```
already gives you an `h1` header, so you do not need to create another `h1` header yourself. What you can do is to modify for instance
```
---
layout: post
title: Week 1 - What is Open Source?
---
```
and remove the line
```
# Week1: What is Open Source?
```
and same for other weekly posts.

**Comment by seoeunHong** [comment]
Hi thanks for suggesting I edited them!
